//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model", "Professionworker", "Profession", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(pr2.Profession), "worker", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(pr2.worker), true)]
[assembly: EdmRelationshipAttribute("Model", "departmentworker", "department", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(pr2.department), "worker", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(pr2.worker), true)]
[assembly: EdmRelationshipAttribute("Model", "type_orderorders", "type_order", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(pr2.type_order), "orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(pr2.orders), true)]
[assembly: EdmRelationshipAttribute("Model", "workerorders", "worker", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(pr2.worker), "orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(pr2.orders), true)]
[assembly: EdmRelationshipAttribute("Model", "workerpj_work_dev", "worker", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(pr2.worker), "pj_work_dev", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(pr2.pj_work_dev), true)]
[assembly: EdmRelationshipAttribute("Model", "deviationpj_work_dev", "deviation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(pr2.deviation), "pj_work_dev", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(pr2.pj_work_dev), true)]

#endregion

namespace pr2
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ModelContainer object using the connection string found in the 'ModelContainer' section of the application configuration file.
        /// </summary>
        public ModelContainer() : base("name=ModelContainer", "ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelContainer object.
        /// </summary>
        public ModelContainer(string connectionString) : base(connectionString, "ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelContainer object.
        /// </summary>
        public ModelContainer(EntityConnection connection) : base(connection, "ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<worker> workerSet
        {
            get
            {
                if ((_workerSet == null))
                {
                    _workerSet = base.CreateObjectSet<worker>("workerSet");
                }
                return _workerSet;
            }
        }
        private ObjectSet<worker> _workerSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Profession> ProfessionSet
        {
            get
            {
                if ((_ProfessionSet == null))
                {
                    _ProfessionSet = base.CreateObjectSet<Profession>("ProfessionSet");
                }
                return _ProfessionSet;
            }
        }
        private ObjectSet<Profession> _ProfessionSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<department> departmentSet
        {
            get
            {
                if ((_departmentSet == null))
                {
                    _departmentSet = base.CreateObjectSet<department>("departmentSet");
                }
                return _departmentSet;
            }
        }
        private ObjectSet<department> _departmentSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<orders> ordersSet
        {
            get
            {
                if ((_ordersSet == null))
                {
                    _ordersSet = base.CreateObjectSet<orders>("ordersSet");
                }
                return _ordersSet;
            }
        }
        private ObjectSet<orders> _ordersSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<type_order> type_orderSet
        {
            get
            {
                if ((_type_orderSet == null))
                {
                    _type_orderSet = base.CreateObjectSet<type_order>("type_orderSet");
                }
                return _type_orderSet;
            }
        }
        private ObjectSet<type_order> _type_orderSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<deviation> deviationSet
        {
            get
            {
                if ((_deviationSet == null))
                {
                    _deviationSet = base.CreateObjectSet<deviation>("deviationSet");
                }
                return _deviationSet;
            }
        }
        private ObjectSet<deviation> _deviationSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<pj_work_dev> pj_work_devSet
        {
            get
            {
                if ((_pj_work_devSet == null))
                {
                    _pj_work_devSet = base.CreateObjectSet<pj_work_dev>("pj_work_devSet");
                }
                return _pj_work_devSet;
            }
        }
        private ObjectSet<pj_work_dev> _pj_work_devSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the workerSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToworkerSet(worker worker)
        {
            base.AddObject("workerSet", worker);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProfessionSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProfessionSet(Profession profession)
        {
            base.AddObject("ProfessionSet", profession);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the departmentSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodepartmentSet(department department)
        {
            base.AddObject("departmentSet", department);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ordersSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToordersSet(orders orders)
        {
            base.AddObject("ordersSet", orders);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the type_orderSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotype_orderSet(type_order type_order)
        {
            base.AddObject("type_orderSet", type_order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the deviationSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodeviationSet(deviation deviation)
        {
            base.AddObject("deviationSet", deviation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the pj_work_devSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopj_work_devSet(pj_work_dev pj_work_dev)
        {
            base.AddObject("pj_work_devSet", pj_work_dev);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class department : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new department object.
        /// </summary>
        /// <param name="id_dep">Initial value of the Id_dep property.</param>
        /// <param name="dep_name">Initial value of the dep_name property.</param>
        public static department Createdepartment(global::System.Int32 id_dep, global::System.String dep_name)
        {
            department department = new department();
            department.Id_dep = id_dep;
            department.dep_name = dep_name;
            return department;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_dep
        {
            get
            {
                return _Id_dep;
            }
            set
            {
                if (_Id_dep != value)
                {
                    OnId_depChanging(value);
                    ReportPropertyChanging("Id_dep");
                    _Id_dep = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_dep");
                    OnId_depChanged();
                }
            }
        }
        private global::System.Int32 _Id_dep;
        partial void OnId_depChanging(global::System.Int32 value);
        partial void OnId_depChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String dep_name
        {
            get
            {
                return _dep_name;
            }
            set
            {
                Ondep_nameChanging(value);
                ReportPropertyChanging("dep_name");
                _dep_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("dep_name");
                Ondep_nameChanged();
            }
        }
        private global::System.String _dep_name;
        partial void Ondep_nameChanging(global::System.String value);
        partial void Ondep_nameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "departmentworker", "worker")]
        public EntityCollection<worker> worker
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<worker>("Model.departmentworker", "worker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<worker>("Model.departmentworker", "worker", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="deviation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class deviation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new deviation object.
        /// </summary>
        /// <param name="id_worker">Initial value of the Id_worker property.</param>
        /// <param name="name_dev">Initial value of the name_dev property.</param>
        public static deviation Createdeviation(global::System.Int32 id_worker, global::System.String name_dev)
        {
            deviation deviation = new deviation();
            deviation.Id_worker = id_worker;
            deviation.name_dev = name_dev;
            return deviation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_worker
        {
            get
            {
                return _Id_worker;
            }
            set
            {
                if (_Id_worker != value)
                {
                    OnId_workerChanging(value);
                    ReportPropertyChanging("Id_worker");
                    _Id_worker = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_worker");
                    OnId_workerChanged();
                }
            }
        }
        private global::System.Int32 _Id_worker;
        partial void OnId_workerChanging(global::System.Int32 value);
        partial void OnId_workerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name_dev
        {
            get
            {
                return _name_dev;
            }
            set
            {
                Onname_devChanging(value);
                ReportPropertyChanging("name_dev");
                _name_dev = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name_dev");
                Onname_devChanged();
            }
        }
        private global::System.String _name_dev;
        partial void Onname_devChanging(global::System.String value);
        partial void Onname_devChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "deviationpj_work_dev", "pj_work_dev")]
        public EntityCollection<pj_work_dev> pj_work_dev
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<pj_work_dev>("Model.deviationpj_work_dev", "pj_work_dev");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<pj_work_dev>("Model.deviationpj_work_dev", "pj_work_dev", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="orders")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class orders : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new orders object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="id_worker">Initial value of the id_worker property.</param>
        /// <param name="id_type">Initial value of the id_type property.</param>
        /// <param name="text_ord">Initial value of the text_ord property.</param>
        /// <param name="date_ord">Initial value of the date_ord property.</param>
        public static orders Createorders(global::System.Int32 id, global::System.Int32 id_worker, global::System.Int32 id_type, global::System.String text_ord, global::System.DateTime date_ord)
        {
            orders orders = new orders();
            orders.Id = id;
            orders.id_worker = id_worker;
            orders.id_type = id_type;
            orders.text_ord = text_ord;
            orders.date_ord = date_ord;
            return orders;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_worker
        {
            get
            {
                return _id_worker;
            }
            set
            {
                Onid_workerChanging(value);
                ReportPropertyChanging("id_worker");
                _id_worker = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_worker");
                Onid_workerChanged();
            }
        }
        private global::System.Int32 _id_worker;
        partial void Onid_workerChanging(global::System.Int32 value);
        partial void Onid_workerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_type
        {
            get
            {
                return _id_type;
            }
            set
            {
                Onid_typeChanging(value);
                ReportPropertyChanging("id_type");
                _id_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_type");
                Onid_typeChanged();
            }
        }
        private global::System.Int32 _id_type;
        partial void Onid_typeChanging(global::System.Int32 value);
        partial void Onid_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String text_ord
        {
            get
            {
                return _text_ord;
            }
            set
            {
                Ontext_ordChanging(value);
                ReportPropertyChanging("text_ord");
                _text_ord = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("text_ord");
                Ontext_ordChanged();
            }
        }
        private global::System.String _text_ord;
        partial void Ontext_ordChanging(global::System.String value);
        partial void Ontext_ordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date_ord
        {
            get
            {
                return _date_ord;
            }
            set
            {
                Ondate_ordChanging(value);
                ReportPropertyChanging("date_ord");
                _date_ord = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_ord");
                Ondate_ordChanged();
            }
        }
        private global::System.DateTime _date_ord;
        partial void Ondate_ordChanging(global::System.DateTime value);
        partial void Ondate_ordChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "type_orderorders", "type_order")]
        public type_order type_order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<type_order>("Model.type_orderorders", "type_order").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<type_order>("Model.type_orderorders", "type_order").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<type_order> type_orderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<type_order>("Model.type_orderorders", "type_order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<type_order>("Model.type_orderorders", "type_order", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "workerorders", "worker")]
        public worker worker
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<worker>("Model.workerorders", "worker").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<worker>("Model.workerorders", "worker").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<worker> workerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<worker>("Model.workerorders", "worker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<worker>("Model.workerorders", "worker", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="pj_work_dev")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pj_work_dev : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new pj_work_dev object.
        /// </summary>
        /// <param name="id_work">Initial value of the id_work property.</param>
        /// <param name="id_dev">Initial value of the id_dev property.</param>
        /// <param name="id">Initial value of the id property.</param>
        public static pj_work_dev Createpj_work_dev(global::System.Int32 id_work, global::System.Int32 id_dev, global::System.Int32 id)
        {
            pj_work_dev pj_work_dev = new pj_work_dev();
            pj_work_dev.id_work = id_work;
            pj_work_dev.id_dev = id_dev;
            pj_work_dev.id = id;
            return pj_work_dev;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_work
        {
            get
            {
                return _id_work;
            }
            set
            {
                Onid_workChanging(value);
                ReportPropertyChanging("id_work");
                _id_work = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_work");
                Onid_workChanged();
            }
        }
        private global::System.Int32 _id_work;
        partial void Onid_workChanging(global::System.Int32 value);
        partial void Onid_workChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_dev
        {
            get
            {
                return _id_dev;
            }
            set
            {
                Onid_devChanging(value);
                ReportPropertyChanging("id_dev");
                _id_dev = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_dev");
                Onid_devChanged();
            }
        }
        private global::System.Int32 _id_dev;
        partial void Onid_devChanging(global::System.Int32 value);
        partial void Onid_devChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "workerpj_work_dev", "worker")]
        public worker worker
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<worker>("Model.workerpj_work_dev", "worker").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<worker>("Model.workerpj_work_dev", "worker").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<worker> workerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<worker>("Model.workerpj_work_dev", "worker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<worker>("Model.workerpj_work_dev", "worker", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "deviationpj_work_dev", "deviation")]
        public deviation deviation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<deviation>("Model.deviationpj_work_dev", "deviation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<deviation>("Model.deviationpj_work_dev", "deviation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<deviation> deviationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<deviation>("Model.deviationpj_work_dev", "deviation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<deviation>("Model.deviationpj_work_dev", "deviation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Profession")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Profession : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Profession object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static Profession CreateProfession(global::System.Int32 id, global::System.String name)
        {
            Profession profession = new Profession();
            profession.id = id;
            profession.name = name;
            return profession;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "Professionworker", "worker")]
        public EntityCollection<worker> worker
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<worker>("Model.Professionworker", "worker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<worker>("Model.Professionworker", "worker", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="type_order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class type_order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new type_order object.
        /// </summary>
        /// <param name="id_type">Initial value of the Id_type property.</param>
        /// <param name="type_name">Initial value of the type_name property.</param>
        public static type_order Createtype_order(global::System.Int32 id_type, global::System.String type_name)
        {
            type_order type_order = new type_order();
            type_order.Id_type = id_type;
            type_order.type_name = type_name;
            return type_order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_type
        {
            get
            {
                return _Id_type;
            }
            set
            {
                if (_Id_type != value)
                {
                    OnId_typeChanging(value);
                    ReportPropertyChanging("Id_type");
                    _Id_type = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_type");
                    OnId_typeChanged();
                }
            }
        }
        private global::System.Int32 _Id_type;
        partial void OnId_typeChanging(global::System.Int32 value);
        partial void OnId_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type_name
        {
            get
            {
                return _type_name;
            }
            set
            {
                Ontype_nameChanging(value);
                ReportPropertyChanging("type_name");
                _type_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("type_name");
                Ontype_nameChanged();
            }
        }
        private global::System.String _type_name;
        partial void Ontype_nameChanging(global::System.String value);
        partial void Ontype_nameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "type_orderorders", "orders")]
        public EntityCollection<orders> orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<orders>("Model.type_orderorders", "orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<orders>("Model.type_orderorders", "orders", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="worker")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class worker : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new worker object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="fname">Initial value of the fname property.</param>
        /// <param name="birthDate">Initial value of the birthDate property.</param>
        /// <param name="adress">Initial value of the adress property.</param>
        /// <param name="passport">Initial value of the passport property.</param>
        /// <param name="id_profession">Initial value of the id_profession property.</param>
        /// <param name="hDate">Initial value of the hDate property.</param>
        /// <param name="lname">Initial value of the lname property.</param>
        /// <param name="id_department_dep">Initial value of the id_department_dep property.</param>
        public static worker Createworker(global::System.Int32 id, global::System.String fname, global::System.DateTime birthDate, global::System.String adress, global::System.String passport, global::System.Int32 id_profession, global::System.DateTime hDate, global::System.String lname, global::System.Int32 id_department_dep)
        {
            worker worker = new worker();
            worker.Id = id;
            worker.fname = fname;
            worker.birthDate = birthDate;
            worker.adress = adress;
            worker.passport = passport;
            worker.id_profession = id_profession;
            worker.hDate = hDate;
            worker.lname = lname;
            worker.id_department_dep = id_department_dep;
            return worker;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fname
        {
            get
            {
                return _fname;
            }
            set
            {
                OnfnameChanging(value);
                ReportPropertyChanging("fname");
                _fname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fname");
                OnfnameChanged();
            }
        }
        private global::System.String _fname;
        partial void OnfnameChanging(global::System.String value);
        partial void OnfnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime birthDate
        {
            get
            {
                return _birthDate;
            }
            set
            {
                OnbirthDateChanging(value);
                ReportPropertyChanging("birthDate");
                _birthDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("birthDate");
                OnbirthDateChanged();
            }
        }
        private global::System.DateTime _birthDate;
        partial void OnbirthDateChanging(global::System.DateTime value);
        partial void OnbirthDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adress
        {
            get
            {
                return _adress;
            }
            set
            {
                OnadressChanging(value);
                ReportPropertyChanging("adress");
                _adress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("adress");
                OnadressChanged();
            }
        }
        private global::System.String _adress;
        partial void OnadressChanging(global::System.String value);
        partial void OnadressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String passport
        {
            get
            {
                return _passport;
            }
            set
            {
                OnpassportChanging(value);
                ReportPropertyChanging("passport");
                _passport = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("passport");
                OnpassportChanged();
            }
        }
        private global::System.String _passport;
        partial void OnpassportChanging(global::System.String value);
        partial void OnpassportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_profession
        {
            get
            {
                return _id_profession;
            }
            set
            {
                Onid_professionChanging(value);
                ReportPropertyChanging("id_profession");
                _id_profession = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_profession");
                Onid_professionChanged();
            }
        }
        private global::System.Int32 _id_profession;
        partial void Onid_professionChanging(global::System.Int32 value);
        partial void Onid_professionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime hDate
        {
            get
            {
                return _hDate;
            }
            set
            {
                OnhDateChanging(value);
                ReportPropertyChanging("hDate");
                _hDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hDate");
                OnhDateChanged();
            }
        }
        private global::System.DateTime _hDate;
        partial void OnhDateChanging(global::System.DateTime value);
        partial void OnhDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lname
        {
            get
            {
                return _lname;
            }
            set
            {
                OnlnameChanging(value);
                ReportPropertyChanging("lname");
                _lname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lname");
                OnlnameChanged();
            }
        }
        private global::System.String _lname;
        partial void OnlnameChanging(global::System.String value);
        partial void OnlnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_department_dep
        {
            get
            {
                return _id_department_dep;
            }
            set
            {
                Onid_department_depChanging(value);
                ReportPropertyChanging("id_department_dep");
                _id_department_dep = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_department_dep");
                Onid_department_depChanged();
            }
        }
        private global::System.Int32 _id_department_dep;
        partial void Onid_department_depChanging(global::System.Int32 value);
        partial void Onid_department_depChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "Professionworker", "Profession")]
        public Profession Profession
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profession>("Model.Professionworker", "Profession").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profession>("Model.Professionworker", "Profession").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Profession> ProfessionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profession>("Model.Professionworker", "Profession");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Profession>("Model.Professionworker", "Profession", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "departmentworker", "department")]
        public department department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("Model.departmentworker", "department").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("Model.departmentworker", "department").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<department> departmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("Model.departmentworker", "department");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<department>("Model.departmentworker", "department", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "workerorders", "orders")]
        public EntityCollection<orders> orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<orders>("Model.workerorders", "orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<orders>("Model.workerorders", "orders", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "workerpj_work_dev", "pj_work_dev")]
        public EntityCollection<pj_work_dev> pj_work_dev
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<pj_work_dev>("Model.workerpj_work_dev", "pj_work_dev");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<pj_work_dev>("Model.workerpj_work_dev", "pj_work_dev", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
